# Generated by Django 3.2 on 2021-04-30 14:09

import common.custom.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(default=1)),
                ('path', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Uploader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploader_id', models.CharField(max_length=32, unique=True)),
                ('uploader', models.CharField(db_index=True, default='', max_length=255)),
                ('uploader_url', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=32, unique=True)),
                ('title', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(null=True)),
                ('upload_date', models.DateField(null=True)),
                ('duration', models.IntegerField(null=True)),
                ('view_count', models.IntegerField(null=True)),
                ('average_rating', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('age_limit', models.IntegerField(null=True)),
                ('like_count', models.IntegerField(null=True)),
                ('dislike_count', models.IntegerField(null=True)),
                ('channel_id', models.CharField(max_length=32, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('thumbnail_resource', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thumbnail_resource_set', to='youtube.resource')),
                ('uploader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='youtube.uploader', to_field='uploader_id')),
                ('video_resource', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_resource_set', to='youtube.resource')),
            ],
        ),
        migrations.CreateModel(
            name='KeywordVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_keyword_set', to='youtube.keyword')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_keyword_set', to='youtube.video', to_field='video_id')),
            ],
            options={
                'db_table': 'youtube_keyword_video',
                'unique_together': {('video_id', 'keyword_id')},
            },
        ),
        migrations.AddField(
            model_name='keyword',
            name='videos',
            field=models.ManyToManyField(through='youtube.KeywordVideo', to='youtube.Video'),
        ),
        migrations.CreateModel(
            name='JobRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255)),
                ('model_id', common.custom.models.UnsignedBigIntegerField()),
                ('task_id', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'youtube_job_relation',
                'unique_together': {('model', 'model_id')},
            },
        ),
        migrations.CreateModel(
            name='VideoThumbnail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail_id', models.CharField(max_length=32)),
                ('height', models.IntegerField(null=True)),
                ('width', models.IntegerField(null=True)),
                ('resolution', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resource', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_thumbnail_resource_set', to='youtube.resource')),
                ('video', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_thumbnail_set', to='youtube.video', to_field='video_id')),
            ],
            options={
                'db_table': 'youtube_video_thumbnail',
                'unique_together': {('video_id', 'thumbnail_id')},
            },
        ),
        migrations.CreateModel(
            name='VideoFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format_id', models.CharField(max_length=32)),
                ('asr', models.IntegerField(null=True)),
                ('filesize', common.custom.models.UnsignedBigIntegerField(null=True)),
                ('format_note', models.CharField(max_length=255, null=True)),
                ('fps', models.IntegerField(null=True)),
                ('height', models.IntegerField(null=True)),
                ('width', models.IntegerField(null=True)),
                ('quality', models.IntegerField(null=True)),
                ('ext', models.CharField(max_length=32, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resource', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_format_resource_set', to='youtube.resource')),
                ('video', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_format_set', to='youtube.video', to_field='video_id')),
            ],
            options={
                'db_table': 'youtube_video_format',
                'unique_together': {('video_id', 'format_id')},
            },
        ),
    ]
