# Generated by Django 3.2 on 2021-04-30 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keyword',
            old_name='videos',
            new_name='video_set',
        ),
    ]
